# shamelessly copied from https://github.com/cranci1/Luna/blob/main/.github/workflows/build.yml

name: Build and upload nightly ipa

on:
 push:
   branches:
     - main

jobs:
 build-ios:
   name: Build iOS IPA
   runs-on: macos-26
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Set up Xcode
       uses: maxim-lobanov/setup-xcode@v1
       with:
         xcode-version: latest-stable

     - name: Make build script executable
       run: chmod +x ./buildipa.sh

     - name: Build iOS IPA
       run: ./buildipa.sh

     - name: Upload IPA
       uses: actions/upload-artifact@v4
       with:
         name: Shirox-Nightly-IPA
         path: build/Shirox.ipa