# shamelessly copied from https://github.com/cranci1/Luna/blob/main/.github/workflows/build.yml

name: Build and upload nightly ipa

on:
 push:
   branches:
     - main

jobs:
 build-ios:
   name: Build iOS IPA
   runs-on: macos-26
   permissions:
     contents: write
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Set up Xcode
       run: sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer

     - name: Make build script executable
       run: chmod +x ./buildipa.sh

     - name: Build iOS IPA
       run: ./buildipa.sh

     - name: Upload IPA
       uses: actions/upload-artifact@v4
       with:
         name: Shirox-Nightly-IPA
         path: build/Shirox.ipa

     - name: Upload IPA to beta release
       env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         gh release create beta --title "beta" --notes "Latest nightly build" 2>/dev/null || true
         gh release upload beta build/Shirox.ipa --clobber